[package]
name = "texter"
version = "0.1.0"
authors = ["Henning Meyer <tutmann@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wiringpi = "0.2"
